language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install hxcpp
  - haxelib install hashlink
  - haxelib dev inotify .

script:
  - haxe haxedoc.hxml
  - make clean ndll
  - haxe --cwd example/ cpp.hxml
  - haxe --cwd example/ hl.hxml
  - haxe --cwd example/ neko.hxml
