language: haxe

os:
  - linux

haxe:
  - "3.2.1"
  - development

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

install:
  - haxelib install hxcpp

script:
  - haxe haxedoc.hxml
  - make ndll
  - make examples

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8484d5a3a9b1b538162e
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # default: false
