language: haxe

os:
  - linux

haxe:
  - "4.0.5"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install hxcpp
  - haxelib install hashlink
  - haxelib dev inotify .

script:
  - haxe haxedoc.hxml
  - haxelib run hxcpp build.xml ndll
  - haxe --cwd example/ cpp.hxml
  - haxe --cwd example/ hl.hxml
  - haxe --cwd example/ neko.hxml
